### ISSUE TITLE
How to decode core dump data from Serial after read from flash like backtrace?

### ISSUE THREAD

**Issue by Huibean** [MathieuDeprez/ESP32_CoreDump_Arduino_1.0.6#7]
this question might be stupid, but can not find a way to decode that data like backtrace

**Comment by HankLloydRight** [comment]
You have to follow the steps starting at #7: 
https://github.com/MathieuDeprez/ESP32_CoreDump_Arduino_1.0.6#7-install-esp-idf-xtensa-and-libncurses5

I got it to work on a CentOS linux box although getting it to work is highly dependent on the PATHs being set correctly and using the proper version of Python (Python 2, I believe).   Won't work with Python3.

Also, on CentOS I didn't need to install the libncurses5 lib.  I'm not sure what that does or why it's needed -I think it's specific to Debian/Ubuntu.

**Comment by Huibean** [comment]
> You have to follow the steps starting at #7: https://github.com/MathieuDeprez/ESP32_CoreDump_Arduino_1.0.6#7-install-esp-idf-xtensa-and-libncurses5
> 
> I got it to work on a CentOS linux box although getting it to work is highly dependent on the PATHs being set correctly and using the proper version of Python (Python 2, I believe). Won't work with Python3.
> 
> Also, on CentOS I didn't need to install the libncurses5 lib. I'm not sure what that does or why it's needed -I think it's specific to Debian/Ubuntu.

look like I have to find a x86 linux

**Comment by Huibean** [comment]
@HankLloydRight luckily get it working with mac M1, thanks a lot
